# Generated by Django 4.2.10 on 2026-03-11 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="城市名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="城市代码"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "城市",
                "verbose_name_plural": "城市列表",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IDC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="机房名称")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="机房编码"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="机房地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idcs",
                        to="hosts.city",
                        verbose_name="所属城市",
                    ),
                ),
            ],
            options={
                "verbose_name": "机房",
                "verbose_name_plural": "机房列表",
                "unique_together": {("name", "city")},
            },
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="主机名"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(unique=True, verbose_name="IP地址"),
                ),
                (
                    "root_password",
                    models.CharField(max_length=255, verbose_name="Root密码（加密）"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "未知"),
                            ("online", "在线"),
                            ("offline", "离线"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="主机状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "idc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosts",
                        to="hosts.idc",
                        verbose_name="所属机房",
                    ),
                ),
            ],
            options={
                "verbose_name": "主机",
                "verbose_name_plural": "主机列表",
                "ordering": ["hostname"],
            },
        ),
        migrations.CreateModel(
            name="HostStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host_count", models.IntegerField(default=0, verbose_name="主机数量")),
                ("statistic_date", models.DateField(verbose_name="统计日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hosts.city",
                        verbose_name="城市",
                    ),
                ),
                (
                    "idc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hosts.idc",
                        verbose_name="机房",
                    ),
                ),
            ],
            options={
                "verbose_name": "主机统计",
                "verbose_name_plural": "主机统计",
                "unique_together": {("city", "idc", "statistic_date")},
            },
        ),
    ]
